#!/usr/bin/env python3
"""
make_logo_header.py - turn a logo image into RGB565 arrays for TFT_eSPI.

The sketch draws a badge on the boot splash and in the status bar. The image
itself is NOT in this repository (a car maker's logo is their trademark), so
generate the header locally from your own file:

    pip install pillow
    python3 tools/make_logo_header.py logo.png

That writes firmware/kwp71_m2104_esp32/logo_data.h with two arrays:
alfaLogo120 (120x120, composed on black, for the splash) and alfaLogo18
(18x18, composed on the status bar colour). Both are ignored by git.

Without the header the sketch still builds: it then shows a text-only splash
and no badge in the status bar.

Options:
  --out PATH     where to write the header
  --big N        splash size in pixels (default 120)
  --small N      status bar size in pixels (default 18)
  --bar RRGGBB   status bar background colour (default 101410, = COL_BAR)
"""
import argparse
import sys

BIG_NAME, SMALL_NAME = "alfaLogo120", "alfaLogo18"


def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def cut_background(im):
    """Make the OUTER background transparent: flood fill near-white (or already
    transparent) pixels inwards from the border. White inside the badge stays,
    so the logo keeps its white half but loses the white square around it."""
    from collections import deque
    px = im.load()
    w, h = im.size

    def is_bg(x, y):
        r, g, b, a = px[x, y]
        return a < 20 or (r > 232 and g > 232 and b > 232)

    seen = bytearray(w * h)
    q = deque()
    for x in range(w):
        for y in (0, h - 1):
            if is_bg(x, y) and not seen[y * w + x]:
                seen[y * w + x] = 1; q.append((x, y))
    for y in range(h):
        for x in (0, w - 1):
            if is_bg(x, y) and not seen[y * w + x]:
                seen[y * w + x] = 1; q.append((x, y))
    while q:
        x, y = q.popleft()
        r, g, b, _ = px[x, y]
        px[x, y] = (r, g, b, 0)
        for nx, ny in ((x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1)):
            if 0 <= nx < w and 0 <= ny < h and not seen[ny * w + nx] and is_bg(nx, ny):
                seen[ny * w + nx] = 1
                q.append((nx, ny))
    return im


def convert(path, size, bg):
    from PIL import Image
    im = cut_background(Image.open(path).convert("RGBA"))
    bbox = im.getchannel("A").point(lambda v: 255 if v > 20 else 0).getbbox()
    if bbox is None:
        sys.exit("image is empty after trimming - is it all white or transparent?")
    # keep the badge round: crop to a square around the visible part
    x0, y0, x1, y1 = bbox
    cx, cy, side = (x0 + x1) // 2, (y0 + y1) // 2, max(x1 - x0, y1 - y0)
    im = im.crop((cx - side // 2, cy - side // 2, cx + side // 2, cy + side // 2))
    im = im.resize((size, size), Image.LANCZOS)
    flat = Image.new("RGB", (size, size), bg)
    flat.paste(im, (0, 0), im)          # alpha-composited onto the target background
    return [rgb565(*flat.getpixel((x, y))) for y in range(size) for x in range(size)]


def emit(name, size, data):
    out = ["const uint16_t %s[%d] = {" % (name, size * size)]
    for i in range(0, len(data), 12):
        out.append("  " + ",".join("0x%04X" % v for v in data[i:i + 12]) + ",")
    out.append("};")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("image", help="source image, e.g. logo.png")
    ap.add_argument("--out", default="firmware/kwp71_m2104_esp32/logo_data.h")
    ap.add_argument("--big", type=int, default=150, help="splash size (default 150)")
    ap.add_argument("--small", type=int, default=20, help="status bar size (default 20)")
    ap.add_argument("--bar", default="101410", help="status bar colour as RRGGBB (default 101410)")
    args = ap.parse_args()

    bar = tuple(int(args.bar[i:i + 2], 16) for i in (0, 2, 4))
    big = convert(args.image, args.big, (0, 0, 0))
    small = convert(args.image, args.small, bar)

    header = ("// Badge bitmaps (RGB565, for TFT_eSPI pushImage), generated by\n"
              "// tools/make_logo_header.py from %s - NOT tracked in git.\n"
              "#pragma once\n#include <Arduino.h>\n\n" % args.image)
    header += ("#define LOGO_BIG_SIZE %d\n#define LOGO_SMALL_SIZE %d\n\n" % (args.big, args.small))
    header += emit(BIG_NAME, args.big, big) + "\n\n" + emit(SMALL_NAME, args.small, small) + "\n"
    with open(args.out, "w") as f:
        f.write(header)
    print("wrote %s (%d + %d pixels, %.1f KB of flash)"
          % (args.out, args.big ** 2, args.small ** 2,
             (args.big ** 2 + args.small ** 2) * 2 / 1024))


if __name__ == "__main__":
    main()
